### PR TITLE
Edited files in order to respect "ESLINT" rules

### PR DESCRIPTION
**Pull request by luizguilhermefr**
Simple contribution by removing some trailing commas and semicolons, and also adding spaces between function parenthesis.

Eslint for React-Native: https://www.npmjs.com/package/eslint-plugin-react-native

### CODE REVIEW

**Comment by ericvicenti** [comment]
Sorry, this is not the code style we use in this project

Edit: oops, I thought this was the react-native repo. Carry on, I'll let others decide!

**Comment by luizguilhermefr** [comment]
Thanks. It isn't personal choice. It's just to avoid headaches in projects that use Eslint, like some of mine.

**Comment by ide** [comment]
Can you use https://github.com/exponent/eslint-config-exponent instead?

**Comment by luizguilhermefr** [comment]
Why not to use the proposed package?
If this repository proposes to serve the community, then the most used library should be used.

**Comment by ide** [comment]
I don't agree with that. You're free to fork this repository if you feel strongly about it.

**Pull request closed without merging**
