### PR TITLE
Support custom styles for enabled/disabled states

### PR DESCRIPTION
**Pull request by evansolomon**

### CODE REVIEW

**Comment by ide** [comment]
What do you think about having just styleEnabled or just styleDisabled (and you'd use whichever we pick to override normal `style`)?

**Comment by evansolomon** [comment]
I think it makes sense to have both because it seems reasonable to have a set of "global" styles for the button (e.g. fonts, padding) and a set of state-specific styles that would likely be more limits (e.g. color). In the particular use case I had in mind I just wanted to change the color.

Obviously that could be done manually by merging objects yourself, but that's a little clunkier.

No super strong feelings, but that's my initial thought.

**Comment by ide** [comment]
I had in mind something like this:

```
// in button.js
style={[this.props.style, disabled ? this.props.styleDisabled : null]}
```

So `style` is always applied, and if you want to change the color when its disabled you'd specify overrides via `styleDisabled`.

**Comment by evansolomon** [comment]
Ah, got it. I don't have a strong opinion either way. That seems reasonable to me.

**Comment by ide** [comment]
Could you update this PR so that it introduces just the `styleDisabled` prop? Looks great otherwise.

**Comment by evansolomon** [comment]
:+1:

**Comment by evansolomon** [comment]
One thing I realized is that now that `props.styleDisabled` exists, it becomes a little unclear whether `props.style` should override the default disabled styling. It did previously (i.e. when it was the only custom style) so I kept it that way here, but just wanted to call it out since it's potentially confusing.

**Comment by ide** [comment]
The behavior you picked seems sane to me. Thanks for your diff!

**Pull request merged**
