### PR TITLE
support borderRadius for button

### LINKED ISSUE #13: Transparency on border radius not working
There is a white background no matter what, how do I remove this?

screen shot 2015-10-23 at 10 54 37 am

```
  button: {
    width: 300,
    height: 60,
    color: '#fff',
    backgroundColor: '#49A8A2',
    borderRadius: 20
  }
```

### PR DESCRIPTION
**Pull request by andrewljohnson**
fixes #13

### CODE REVIEW

**Comment by andrewljohnson** [comment]
fixes #13

**Comment by Elyx0** [comment]
Why not merged yet ?

**Comment by ide** [comment]
@Elyx0 we don't take every PR. if it's really important to you, fork this repo.

**Comment by andrewljohnson** [comment]
@ide was this the wrong approach... any feedback on my PR?

**Comment by ide** [comment]
The Text style and TouchableOpacity style probably should be kept separate. Can you introduce a new containerStyle prop and use that instead?

**Comment by andrewljohnson** [comment]
:thumbsup:

**Pull request closed without merging**
